#======================================#
#========== Spring settings ===========#
#======================================#
spring:
  #当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles: dev
  #======================================#
  #========== Database settings =========#
  #======================================#
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/test?#useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: test
    password: test123
    # DRUID连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: false

#======================================#
#=========== Log settings =============#
#======================================#
logging:
  config: classpath:config/logback-spring.xml

